name: Nasa Project Continuous Integration
on: 
  push:
    branches: [ master ]
  pull_request: 
    branches: [ master ]
jobs:
  build: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - run: yarn
      - run: cd client && yarn run build